### ISSUE TITLE
Offset for spell damage component of melee hits

### ISSUE THREAD

**Issue by grlffchrs** [Justw8/NameplateSCT#18]
As a protection paladin using seal of righteousness, the normal damage and spell damage component of the melee hit are shown right on top of each other when using "vertical up".
Being able to specify an offset for the spell damage component could solve this issue.
![WoWScrnShot_092821_120231](https://user-images.githubusercontent.com/42968002/135066822-4fa60612-a0b3-4f2c-84a7-4c80bcdd62ba.jpg)

**Comment by Justw8** [comment]
I don't plan on adding/fixing this.
