### ISSUE TITLE
Hosting on alternative addon site?

### ISSUE THREAD

**Issue by Daegalus** [Justw8/NameplateSCT#19]
With the API changes to Curseforge, would it be possible for you to upload the addon to WoWInterface, WoWup, or wago? This way many third party addon managers can continue getting updates.

Or if not, permission for someone to upload them to an alternate site for you with appropriate disclaimers?

WoWUp doesn't even need an upload, just pointing them to this github: https://wowup.io/guide/wowup/hub

**Comment by Justw8** [comment]
I do not plan to host it anywhere else. Curseforge is fine.
