### ISSUE TITLE
Feature request: Option to hide decimal when truncating number

### ISSUE THREAD

**Issue by veev-code** [Justw8/NameplateSCT#23]
When truncating numbers it would be great to have an option to hide the decimal value.

E.g., `2.8k` -> `2k` (hide with floor) or `3k` (hide with round).

This would reduce noise and allow numbers like `28k` to be be more noticeable.

Thanks for the excellent addon!

**Comment by Justw8** [comment]
If you want to see more precise numbers I'm not sure this is the addon for that, as it can get quite messy with a lot of events.
The truncating feature is to clean up the screen more, not to make big numbers more noticeable. So I'm not planning on giving more options for that as of now.

**Comment by veev-code** [comment]
@Justw8 Just to clarify, I don't want precise numbers and my request was to even _further_ truncate the numbers. E.g., to truncate the current `2.8k` to `2k`. An option to show no decimal places.
