### ISSUE TITLE
Immune Spam in v10.0.7

### ISSUE THREAD

**Issue by ljlevend** [Justw8/NameplateSCT#24]
I get very rapid Immune spam for certain types of mobs since v10.0.7 (i.e., the text "Immune" pours out of mobs' health bars). You can reproduce the issue on Boulderfist in Valdrakken. I'm playing a Protection Paladin, but not sure if that matters.

**Comment by kgwium** [comment]
I want to add this image here for you to see what he is about.

![image_2023-03-24_044951642](https://user-images.githubusercontent.com/40608423/227427155-e99549ed-9ba3-46e3-9de6-b36cf8e54140.png)

**Comment by ljlevend** [comment]
This seems to be caused when certain mobs (possibly mobs that are immune to cc) are standing in a paladin's Consecration spell. Adding Consecration to the filter list in NameplateSCT eliminates the issue, but also prevents Consecration's damage from being shown.

**Comment by Justw8** [comment]
You can remove Immune flags by disabling the miss/parry/dodge/etc events.

https://i.imgur.com/ueazZ40.png

This will not display them anymore, and might be what you're looking for.

**Comment by kgwium** [comment]
> You can remove Immune flags by disabling the miss/parry/dodge/etc events.
> 
> ![image](https://user-images.githubusercontent.com/15148726/227808632-77057273-684b-48ad-b9b1-719d77cdceeb.png)
> 
> This will not display them anymore, and might be what you're looking for.



apologies for opening this one up again,  under wich section is that Miss/Parry/Dodge/etc under ?
for some reason,  I am unable to find it for some reason.
