### ISSUE TITLE
Overkill text

### ISSUE THREAD

**Issue by Eiganjos** [Justw8/NameplateSCT#25]
Hello,

Would it be possible to have the text of the overkill in the same way? That is to say on the nameplate of the enemy?

I love your addon, and it's only this point that puts me off. But thanks a lot !

Best regards,

**Comment by Justw8** [comment]
When an enemy is killed, their nameplate also disappears. There is the overkill feature implemented for this specifically, as otherwise you don't see it at all anymore. Beyond that it's not possible.
