### ISSUE TITLE
Skill icons are displayed over healthbar while damage numbers are below

### ISSUE THREAD

**Issue by liujiaruirz** [Justw8/NameplateSCT#28]
Hi, I set the layers of combat texts as background, but it seems only the numbers are on the background layer and the skill icons are not. Any solutions to also move icons below? Thanks.

**Comment by Toxicom** [comment]
Can confirm, very annoying
![image](https://github.com/Justw8/NameplateSCT/assets/69549795/e68a7682-c5d0-4104-bc0c-7a3a262d1ea9)

**Comment by Toxicom** [comment]
Feel like this is related to the same issue -- Alpha slider has no impact on icon either
![image](https://github.com/Justw8/NameplateSCT/assets/69549795/17b80c13-83ac-424d-a2dd-6f8f2274ac84)
![image](https://github.com/Justw8/NameplateSCT/assets/69549795/2b29d038-b8f2-47f7-a236-6460e0bef0ad)

@Justw8 any update on the issue, should we be expecting fixes any time soon?

**Comment by Justw8** [comment]
I was able to reproduce this myself, but I had not been able to fix it. It'll remain open until we do someday.

**Comment by Justw8** [comment]
Finally fixed this in the latest 1.35 release.
