### ISSUE TITLE
No text is displayed when damaging structures

### ISSUE THREAD

**Issue by stdNullPtr** [Justw8/NameplateSCT#29]
Currently when in a battleground and damaging structures, no damage text is being displayed.
No damage is displayed, neither with bombs nor siege vehicles.
Using default settings fresh addon install.

**Comment by Blazej-oWo** [comment]
Hey, try to download this addon https://www.curseforge.com/wow/addons/libsharedmedia-3-0 it helped me.

**Comment by Justw8** [comment]
I think the issue here is that it only displays damage you do, and vehicle damage is not tracked as 'you', in addition to that: do structures even have nameplates?

**Comment by stdNullPtr** [comment]
They have health, without the addon you can see damage text

**Comment by Justw8** [comment]
yes, but without addon it's from blizzard. they don't require nameplates.

**Comment by Justw8** [comment]
Closing this as there wont be support for buildings/anything without a nameplate.
