### ISSUE TITLE
Feature request: round to whole number

### ISSUE THREAD

**Issue by mana-break** [Justw8/NameplateSCT#32]
Hello! Thanks for the addon!

It would be convenient to round the numbers to the nearest whole number. For example 123k instead of 123.4k. The numbers after the decimal point have no informational value and are just noise.

And, accordingly, automatically hide combat text below 1k.

**Comment by Justw8** [comment]
Added a slider to set a number of which you would like to filter any events from.
I will not adjust the truncated numbers formatting right now.
