### ISSUE TITLE
Showing text even when far away

### ISSUE THREAD

**Issue by jmpalomares** [Justw8/NameplateSCT#33]
Hi,

Not sure if this is implemented already and I didn't see it but, was wondering if is possible to add a feature to see the damage similar as the overkill when the enemy is too far away and the nameplate is not showed. Sometimes I'm hitting enemies too far and can't see the numbers.

I don't think this is hard to achive. Perhaps I can do it myself with a PR but wanted to be sure before.

Thanks.

**Comment by jmpalomares** [comment]
Btw this is for classic wow, this happens because un vanilla wow the nameplates is like 20 yards max but some spells can hit farder.

**Comment by Justw8** [comment]
Not planning on adding this.
