### ISSUE TITLE
Taken Damage Show

### ISSUE THREAD

**Issue by ekrrkaan** [Justw8/NameplateSCT#35]
Apart from the damage I dealt, it also shows the taken damage and absorb I received, and I do not want to see the damage that I absorbed and received, I could not see any settings on the addon. What should I do ?

**Comment by Justw8** [comment]
You disable it by unticking the option of `Personal SCT`

**Comment by ekrrkaan** [comment]
its untick but still shows :P

**Comment by Justw8** [comment]
could you show a screenshot of it working while it's not checked? since that is impossible in the code >_>

**Comment by Justw8** [comment]
I tested this myself today, seems to be working fully as intended.
