### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by BlueNightSky** [Justw8/NameplateSCT#39]
10x NameplateSCT/NameplateSCT.lua:1012: bad argument #1 to 'GetSpellTexture' (Usage: local iconID, originalIconID = C_Spell.GetSpellTexture(spellIdentifier))
[string "=[C]"]: ?
[string "@NameplateSCT/NameplateSCT.lua"]:1012: in function `DisplayText'
[string "@NameplateSCT/NameplateSCT.lua"]:974: in function `MissEvent'
[string "@NameplateSCT/NameplateSCT.lua"]:771: in function <NameplateSCT/NameplateSCT.lua:730>
[string "=(tail call)"]: ?
[string "@!Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ns/!Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@!Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ns/!Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@!Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@!Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <!Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
(*temporary) = nil

**Comment by Justw8** [comment]
I've added a fallback to avoid this, not sure what the cause is as I would like to know the event as well. Let me know incase some spell does not show up.
