### ISSUE TITLE
1.39

### ISSUE THREAD

**Issue by kiruz-0** [Justw8/NameplateSCT#42]
Hi,
I downloaded 1.39 but Im still having same issue. Any idea what might be causing it? Other addonds? I can go to settings and change stuff, but it has no effect.

1064x NameplateSCT/NameplateSCT.lua:925: attempt to compare number with nil
[string "@NameplateSCT/NameplateSCT.lua"]:925: in function `DamageEvent'
[string "@NameplateSCT/NameplateSCT.lua"]:771: in function <NameplateSCT/NameplateSCT.lua:739>
[string "=(tail call)"]: ?
[string "@AllTheThings/lib/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@AllTheThings/lib/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@AllTheThings/lib/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@BlizzMove/Libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <BlizzMove/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
self = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 menu = Frame {
 }
 baseName = "NameplateSCT"
 name = "NameplateSCT"
 orderedModules = <table> {
 }
 db = <table> {
 }
 enabledState = true
 defaultModuleState = true
 frame = Frame {
 }
}
guid = "Creature-0-4234-2444-9721-193302-000022B1CA"
spellName = "Keg Smash"
amount = 34678
overkill = -1
school = 1
crit = false
spellId = 121253
absorbed = nil
amount = 34678
absorbed = 0
(*temporary) = nil
(*temporary) = 34678
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare number with nil"
playerGUID = "Player-3713-0ABE8D5E"
guidToUnit = <table> {
 Creature-0-4234-2444-9721-191404-000022B17F = "nameplate2"
 Creature-0-4234-2444-9721-193302-000022B1CA = "nameplate1"
}
NameplateSCT = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 menu = Frame {
 }
 baseName = "NameplateSCT"
 name = "NameplateSCT"
 orderedModules = <table> {
 }
 db = <table> {
 }
 enabledState = true
 defaultModuleState = true
 frame = Frame {
 }
}
L = <table> {
 BlizzardSCT = "BlizzardSCT"
 Auto Attacks = "Auto Attacks"
 Truncate Method:

Western:
  1000=>1K,
  1000K=>1M
Asia East:
  10000=>1w = "Truncate Method:

Western:
  1000=>1K,
  1000K=>1M
Asia East:
  10000=>1w"
 Right = "Right"
 Embiggen Crits = "Embiggen Crits"
 Parried = "Parried"
 Immune = "Immune"
 Display Off-Target Text = "Display Off-Target Text"
 Shake = "Shake"
 Icon Scale = "Icon Scale"
 Let Masuqe skin the icons = "Let Masuqe skin the icons"
 Font Flags = "Font Flags"
 NPCs = "NPCs"
 Hide Small Hits = "Hide Small Hits"
 Bottom = "Bottom"
 Y Variance = "Y Variance"
 Scale down hits that are below a running average of your recent damage output = "Scale down hits that are below a running average of your recent damage output"
 Alpha = "Alpha"
 %s (A: %s) = "%s (A: %s)"
 Personal SCT = "Personal SCT"
 Reflected = "Reflected"
 Default Color = "Default Color"
 Default speed: 1 = "Default speed: 1"
 Show Absorbed Damage shown as: '5 (A: 3)' where A: 3 is the absorbed amount = "Show Absorbed Damage shown as: '5 (A: 3)' where A: 3 is the absorbed amount"
 Bottom Right = "Bottom Right"
 Y Offset = "Y Offset"
 Show Truncated Letter = "Show Truncated Letter"
 Appearance/Offsets = "Appearance/Offsets"
 Display Overkill = "Display Overkill"
 Disabled = "Disabled"
 Y Offset Personal SCT = "Y Offset Personal SCT"
 X Variance = "X Variance"
 High = "High"
 X Offset = "X Offset"
 X Offset Personal SCT = "X Offset Personal SCT"
 Western = "Western"
 Do Not Truncate = "Do Not Truncate"
 Use Crit Color = "Use Crit Color"
 Vertical Up = "Vertical Up"
 Enable Masque = "Enable Masque"
 Resisted = "Resisted"
 Vertical Down = "Vertical Down"
 Size = "Size"
 Rainfall = "Rainfall"
 Use Separate Off-Target Strata = "Use Separate Off-Target Strata"
 Use Damage Type Color = "Use Damage Type Color"
 Truncate Number = "Truncate Number"
 Truncate Letter East Asia = "Truncate Letter East Asia"
 Monochrome = "Monochrome"
 Hide hits that are below this threshold. = "Hide hits that are below this threshold."
 Top = "Top"
 Low = "Low"
 Font = "Font"
 Default = "Default"
 Position = "Position"
 Thick Outline = "Thick Outline"
 Text Shadow = "Text Shadow"
 Has soft max/min, you can type whatever you'd like into the editbox = "Has soft max/min, you can type whatever you'd like into the editbox"
 Bottom Left = "Bottom Left"
 Embiggen Crits Scale = "Embiggen Crits Scale"
 Top Left = "Top Left"
 Off-Target Strata = "Off-Target Strata"
 Off-Target Text Appearance = "Off-Target Text Appearance"
 Enable = "Enable"
 Criticals = "Criticals"
 Left = "Left"
 Top Right = "Top Right"
 Scale Down Small Hits = "Scale Down Small Hits"
 Icon X Offset = "Icon X Offset"
 Spells = "Spells"
 Target Strata = "Target Strata"
 Spellid/Spellname seperated by line

White hits/melee = melee =

**Comment by Justw8** [comment]
Try going all the way down in options and changing the small number slider to something, and then back to 0

**Comment by kiruz-0** [comment]
That fixed it after I maxed this settings. Thank you!
