### ISSUE TITLE
1.20.1-2-alpha  - AceLocale-3.0 Issue

### ISSUE THREAD

**Issue by behub-torch** [Justw8/NameplateSCT#5]
In the AceLocale-3.0 folder is actually 'AceGUI-3.0' files so the game throws an error about missing files. I even manually downloaded the addon from twitch to confirm that's how it downloads.

Once that is fixed (I manually replaced missing files) it then complains about a missing locale

```
8x AceLocale-3.0-6: NameplateSCT: Missing entry for 'Critical'
[string "@NameplateSCT\NameplateSCT-1.20.lua"]:1047: in main chunk
```

**Comment by Justw8** [comment]
I see the same issue, not sure why. Looking into it.

**Comment by Justw8** [comment]
Fixed this, if the issue with missing locales show up please open a separate ticket.
