### ISSUE TITLE
Inverse filtering doesn't work on retail.

### ISSUE THREAD

**Issue by hianick** [Justw8/NameplateSCT#52]
https://www.youtube.com/watch?v=qJgBrpbsJPg

Frost fever is the icon of the head with a frozen brain.
First, I have no filter and it shows up, then I filter "Frost Fever" and it doesn't show up, as expected. When I click inverse and type "Frost Fever" it no longer shows the damage numbers. Even after a reload.

**Comment by Justw8** [comment]
I believe I did fix this a while ago, forgot to post here.
