### ISSUE TITLE
Option to hide Immune hits

### ISSUE THREAD

**Issue by ljosberinn** [Justw8/NameplateSCT#54]
E.g. as (Devastation) Evoker, channeling Disintegrate is a major part of what you're doing and some elites and later obviously bosses are immune to slows via the Natural Convergence talent

![image](https://github.com/user-attachments/assets/b23a6ad7-74a7-4cbf-820c-7d1ce7652bce)

**Comment by Justw8** [comment]
There is a immune/parry etc dropdown which you can set to 'none' to not show them at all iirc.

**Comment by ljosberinn** [comment]
got it, idk how I missed it before, cheers
