### ISSUE TITLE
Damage texts disappear when target dies

### ISSUE THREAD

**Issue by VKupliauskis** [Justw8/NameplateSCT#7]
Killing the enemy makes all the texts disappear, making you miss the few damage numbers that made you kill the target.

Feels very abrupt. Please fix

**Comment by Justw8** [comment]
This is a restriction by blizzard as it prevents us from obtaining the Nameplate positioning. So when a nameplate disapears, so will the text as we do not know where to keep animating the text.

There is a PR available which, when a unit dies, places the numbers on the top of your screen. You can try using that, but I do not support that yet.

**Comment by hoodsy** [comment]
Would it be possible to show the killing/overkill damage where the last damage number for the target was shown?

**Comment by agemennon675** [comment]
Came here to say exactly this, when target dies, the killing blow numbers does not show up on the screen

**Comment by mike-robertson** [comment]
Any chance of putting in PR https://github.com/Justw8/NameplateSCT/pull/6 into the addon? Maybe modifying that to put it behind a config if you don't think that's something that should happen by default (tbh idk much about wow addons but I assume there is some way to access those vars in the script)? I realize I can just copy over the script, but I'm assuming most people don't get that far and it seems to be a pretty requested feature.

Regardless, thanks for the great addon! Lots of fun to watch the numbers bounce around!

**Comment by mike-robertson** [comment]
I decided to try it out and came up with this: https://github.com/Justw8/NameplateSCT/pull/13

I think it can be expanded on by adding offset positioning settings to this as well to allow people to put it where they want instead of just putting it directly on your character's nameplate. Not sure if there is a better way to achieve that.

**Comment by mike-robertson** [comment]
Ok, I think I have a fix pushed up for that, but you are going to want to double check my work here since I'm basically googling this + using existing code to understand the syntax.

**Comment by Justw8** [comment]
The above is in the alpha now!
