### ISSUE TITLE
Font keeps changing

### ISSUE THREAD

**Issue by Hansrutger** [Justw8/NameplateSCT#9]
I have changed all my chars fonts to "Friz Quadrata TT", but every now and then it keeps resetting back to "Bazooka". Not really sure what causes this at all.

**Comment by Justw8** [comment]
mhmm, this might be some default setting returning, as Bazooka is coded to be set as default. I will check it out.

**Comment by Hansrutger** [comment]
I just noticed I had the "ClassicNumbers" addon enabled (but it is disabled in-game, it just shows up on Interface list) as I used it before I found this addon. Maybe it had to do something with that, will check.

**Comment by Justw8** [comment]
Is this still an issue?

**Comment by Justw8** [comment]
Closing.
